### PR TITLE
fix: handle bitcoin uri

### LINKED ISSUE #271: Gateway: withdraw should parse bitcoin uri
Withdraw should parse bitocin uri.

### PR DESCRIPTION
**Pull request by Kodylow**
basic bitcoin uri handling, can make more robust and check network other address features once we merge network awareness (tb1 vs bc1 etc).

Fixes #271

### CODE REVIEW

File: apps/gateway-ui/src/components/WithdrawCard.tsx [hunk 1]
```diff
@@ -45,13 +45,29 @@ export const WithdrawCard = React.memo(function WithdrawCard({
   const [address, setAddress] = useState<string>('');
   const [amount, setAmount] = useState<number>(0);
 
+  const handleBitcoinUri = (address: string) => {
+    const uri = new URL(address);
+    const amt = uri.searchParams.get('amount');
+    if (amt) {
+      setAmount(parseFloat(amt));
+    }
```
Comment (wbobeirne) [inline apps/gateway-ui/src/components/WithdrawCard.tsx]: Amounts are in BTC, not sats
https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#user-content-Transfer_amount

File: apps/gateway-ui/src/components/WithdrawCard.tsx [hunk 2]
```diff
@@ -45,13 +45,29 @@ export const WithdrawCard = React.memo(function WithdrawCard({
...
+  };
+
   const createWithdrawal = useCallback(() => {
     if (amount <= 0) {
       return setError(`${t('withdraw-card.error-amount')}`);
     }
     if (!address) {
       return setError(`${t('withdraw-card.error-address')}`);
     }
+    if (address.startsWith('bitcoin:')) {
```
Comment (wbobeirne) [inline apps/gateway-ui/src/components/WithdrawCard.tsx]: case insensitive

Comment (wbobeirne) [reply apps/gateway-ui/src/components/WithdrawCard.tsx]: move above previous conditionals

**Review by wbobeirne — APPROVED** [review]

**Review by okjodom — APPROVED** [review]
